import type { Metadata } from "next";
import { ArrowUpRight, BriefcaseBusiness, ChartNoAxesCombined, CircleDollarSign, Landmark } from "lucide-react";
import SubpageHeader from "../components/subpage-header";

export const metadata: Metadata = { title: "Indicadores del país", description: "Indicadores económicos oficiales y seguimiento verificable a mecanismos asesores del Gobierno.", alternates: { canonical: "/indicadores" } };
const indicators = [
  { icon: ChartNoAxesCombined, label: "Inflación anual", value: "6,24%", period: "Agosto de 2026", detail: "IPC mensual 0,39% · año corrido 5,35%", source: "DANE", url: "https://www.dane.gov.co/index.php/estadisticas-por-tema/precios-y-costos/indice-de-precios-al-consumidor-ipc/ipc-informacion-tecnica" },
  { icon: BriefcaseBusiness, label: "Desocupación nacional", value: "8,1%", period: "Julio de 2026", detail: "0,7 puntos menos que en julio de 2025", source: "DANE", url: "https://www.dane.gov.co/" },
  { icon: CircleDollarSign, label: "TRM", value: "$3.192,53", period: "22 de septiembre de 2026", detail: "Pesos colombianos por dólar", source: "Banco de la República", url: "https://www.banrep.gov.co/es/glosario/tasa-cambio-trm" },
  { icon: Landmark, label: "PIB real", value: "3,5%", period: "Segundo trimestre de 2026", detail: "Variación anual preliminar", source: "DANE", url: "https://www.dane.gov.co/index.php/component/content/category/138-espanol/58-boletines/118-cuentas-y-sintesis-nacionales?Itemid=109" },
];
export default function IndicatorsPage() { return <main className="subpage country-indicators"><SubpageHeader /><section className="subpage-hero"><p className="section-kicker">CONTEXTO DEL PAÍS</p><h1>Datos para medir<br />el mandato.</h1><p>Indicadores oficiales para observar la evolución económica sin atribuir automáticamente cada cambio al Gobierno.</p></section><section className="subpage-content"><div className="country-indicator-grid">{indicators.map(({ icon: Icon, ...item }) => <article key={item.label}><Icon /><span>{item.label}</span><strong>{item.value}</strong><time>{item.period}</time><p>{item.detail}</p><a href={item.url} target="_blank" rel="noreferrer">{item.source}<ArrowUpRight size={14} /></a></article>)}</div><section className="advisory-tracker"><p className="section-kicker">CAPACIDAD Y ASESORÍA</p><h2>Comité de sabios y banco de talentos</h2><p>Este seguimiento registrará integrantes, reuniones, recomendaciones, nombramientos derivados y resultados únicamente cuando existan actos oficiales o fuentes trazables. Una mención pública no se contará como resultado.</p><div><article><strong>Comité de sabios</strong><span>Sin resultados oficiales suficientes para calcular efectividad</span><p>La efectividad se medirá como recomendaciones publicadas, decisiones vinculadas y cumplimiento verificable.</p></article><article><strong>Banco de talentos</strong><span>Seguimiento documental activo</span><p>Se compararán convocatorias, candidatos reportados, nombramientos y permanencia, sin publicar datos personales no oficiales.</p></article></div><a href="/nombramientos">Consultar nombramientos y reuniones<ArrowUpRight size={14} /></a></section></section></main>; }
